name: Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt clean compile
        run: |
          sbt clean compile
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt stage deployHeroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          ORDER_CORE_URL: https://dev-kezek-customer-core.herokuapp.com/api
          LOG_LEVEL: DEBUG
          HOST: 0.0.0.0
          SWAGGER_SCHEMES: https
          ENV: dev
        run: |
          sbt -Denv=dev stage deployHeroku